### ISSUE TITLE
Clean-up and consolidate pulse/channel parameters

### ISSUE THREAD

**Issue by CoherenceController** [BBN-Q/Qlab#14]
* [x] ~~Move more sequence file boilerplate to parameter files~~
* [x] ~~No hardcoding of marker channels~~
* [ ] Move to logical rather than IQkey keys
* [x] ~~Consolidate fixedPts and cycleLengths~~

**Comment by blakejohnson** [comment]
PatternGen is now deprecated. Use QGL (in PyQLab) instead.
