### ISSUE TITLE
CalibratePulses not working

### ISSUE THREAD

**Issue by mattai1986** [BBN-Q/Qlab#24]
I've tried running calibratepulses and after it compiles the first 8- sequences and takes that data if fails with this error message:

Attempted to access data(0); index must be a positive integer or logical.

Error in PulseCalibration.analyzeRabiAmp (line 20)
    if data(end/2) > offset

Error in PulseCalibration/PulseCalibrationDo (line 46)
   [piAmpGuesses(1), offsetPhases(1)] = obj.analyzeRabiAmp(data(1:end/2));

Error in PulseCalibration/Do (line 207)
            obj.PulseCalibrationDo();

Error in calibratePulses (line 32)
pulseCal.Do();

So it looks like it just isn't taking any data. I changed the ExpParams.measurements from M1 to the new M1_KernalIntegrator that we are using. Not sure if this is correct though.

Any Ideas?

**Comment by matthewware** [comment]
I don't have any insight at the moment.  For the record you're on the develop branch at a commit somewhere around 1/12/15 right?  Could you run 

    git log

Or see what the last commit was?

**Comment by mattai1986** [comment]
It looks like the last commit was on 1/16/15.

**Comment by matthewware** [comment]
Can you tell me the comment or the commit hash?  There were some changes made that day to some of the objective function code.

**Comment by matthewware** [comment]
This issue was fixed in ee3dbc1.
