### ISSUE TITLE
Disable un-used AWGs in PulseCalibration

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/Qlab#26]
The problem is that if you have AWGs enabled that aren't used when calibrating a particular qubit, then you will either get an error in `PulseCalibration.loadSequence()` or you will have bad/dummy data coming out of an AWG. We should disable those AWGs not used in calibrating a particular qubit.

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/Qlab/commit/030f5996bd1228f2dd2bab099aed09fd1f3699f7, https://github.com/BBN-Q/Qlab/commit/37f853c2baa47724d499cf61c109e5c01a595cb0, https://github.com/BBN-Q/Qlab/commit/f1fa72cce51fad0292a7d92239743d7c37b52673. It could be adapted to use metaFile info similar to https://github.com/BBN-Q/Qlab/commit/114fa52b96483f8fc6fd20e99bd6b1f197a213fd.

**Comment by blakejohnson** [comment]
Yes, I think all of these can get cleaned up with meta file data.
