### ISSUE TITLE
Inverse in QST_LSQ

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/Qlab#33]
`inverse` is used in `QST_LSQ.m` [here](https://github.com/BBN-Q/Qlab/blob/a718e9f9eee662f8fc486fcd865d434dea7b499a/analysis/cQED_dataAnalysis/QST_LSQ.m#L27).  Should this be `inv` or `\`?  Maybe I'm missing a library

**Comment by blakejohnson** [comment]
You need the "Factorize" package. The link is listed on the wiki:
https://github.com/BBN-Q/Qlab/wiki/Software-Setup

**Comment by matthewware** [comment]
Thanks Blake!
